name: Bug
description: Reproducible Orientation defect
title: ""
labels: []
body:
  - type: textarea
    id: behavior
    attributes:
      label: Observed behavior
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
