services:
  valhalla:
    image: ghcr.io/valhalla/valhalla-scripted:3.8.3
    ports:
      - "127.0.0.1:8002:8002"
    environment:
      tile_urls: https://download.geofabrik.de/europe/germany/hamburg-260801.osm.pbf
      build_elevation: "False"
      build_admins: "True"
      build_time_zones: "True"
      build_transit: "False"
      build_tar: "True"
      serve_tiles: "True"
      server_threads: "2"
    volumes:
      - valhalla-data:/custom_files

volumes:
  valhalla-data:
